apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-status-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" # User applications
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  sources:
    - repoURL: https://vizzletf.github.io/cluster-status-app
      chart: cluster-status-app
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/values/unused/cluster-status-app.yaml
    - repoURL: git@github.com:VizzleTF/home-proxmox-values.git
      targetRevision: HEAD
      ref: values
    - repoURL: git@github.com:VizzleTF/home-proxmox-values.git
      path: manifests/unused/cluster-status
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
