apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-rag
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Databases before apps that need them
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: "*"
      chart: cluster
      helm:
        valueFiles:
          - $values/values/unused/cnpg-rag.yaml
    - repoURL: git@github.com:VizzleTF/home-proxmox-values.git
      targetRevision: HEAD
      ref: values
    - repoURL: git@github.com:VizzleTF/home-proxmox-values.git
      path: manifests/unused/cnpg-rag
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-rag
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
