apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5" # CNI must be first
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  sources:
    - repoURL: https://helm.cilium.io/
      chart: cilium
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/values/infrastructure/cilium.yaml
    - repoURL: git@github.com:VizzleTF/home-proxmox-values.git
      targetRevision: HEAD
      ref: values
    - repoURL: git@github.com:VizzleTF/home-proxmox-values.git
      path: manifests/infrastructure/cilium
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: cilium-ca
      jqPathExpressions:
        - .data
    - group: ""
      kind: Secret
      name: hubble-relay-client-certs
      jqPathExpressions:
        - .data
    - group: ""
      kind: Secret
      name: hubble-server-certs
      jqPathExpressions:
        - .data
    - group: discovery.k8s.io
      kind: EndpointSlice
      jqPathExpressions:
        - .endpoints[]?.conditions
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jqPathExpressions:
        - .spec.parentRefs[]?.group
        - .spec.parentRefs[]?.kind
        - .spec.rules[]?.backendRefs[]?.group
        - .spec.rules[]?.backendRefs[]?.kind
        - .spec.rules[]?.backendRefs[]?.weight
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: cilium-gateway
      jqPathExpressions:
        - .spec.listeners[]?.tls?.certificateRefs[]?.group
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
