apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  sources:
    - repoURL: https://immich-app.github.io/immich-charts
      chart: immich
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/values/applications/immich.yaml
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cluster
      targetRevision: "0.4.0"
      helm:
        valueFiles:
          - $values/values/applications/cnpg-immich-db.yaml
    - repoURL: git@github.com:VizzleTF/home-proxmox-values.git
      targetRevision: HEAD
      ref: values
    - repoURL: git@github.com:VizzleTF/home-proxmox-values.git
      targetRevision: HEAD
      path: manifests/applications/immich
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jqPathExpressions:
        - .spec.rules[]?.backendRefs[]?.group
        - .spec.rules[]?.backendRefs[]?.kind
        - .spec.rules[]?.backendRefs[]?.weight
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
