apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: may
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  sources:
    - repoURL: https://github.com/VizzleTF/home_proxmox.git
      path: charts/may
      targetRevision: HEAD
    - repoURL: git@github.com:VizzleTF/home-proxmox-values.git
      path: manifests/applications/may
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: may
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
