{{- if or .Values.advancedConfig.databaseUrl .Values.advancedConfig.apiId .Values.advancedConfig.tProxy .Values.advancedConfig.rProxy .Values.advancedConfig.multiuser .Values.advancedConfig.cronSecond .Values.advancedConfig.errorLoggingChat .Values.advancedConfig.debug }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rss-to-telegram-bot.fullname" . }}
  labels:
    {{- include "rss-to-telegram-bot.labels" . | nindent 4 }}
data:
  {{- if .Values.advancedConfig.databaseUrl }}
  DATABASE_URL: {{ .Values.advancedConfig.databaseUrl | quote }}
  {{- end }}
  {{- if .Values.advancedConfig.apiId }}
  API_ID: {{ .Values.advancedConfig.apiId | quote }}
  {{- end }}
  {{- if .Values.advancedConfig.tProxy }}
  T_PROXY: {{ .Values.advancedConfig.tProxy | quote }}
  {{- end }}
  {{- if .Values.advancedConfig.rProxy }}
  R_PROXY: {{ .Values.advancedConfig.rProxy | quote }}
  {{- end }}
  {{- if .Values.advancedConfig.multiuser }}
  MULTIUSER: {{ .Values.advancedConfig.multiuser | quote }}
  {{- end }}
  {{- if .Values.advancedConfig.cronSecond }}
  CRON_SECOND: {{ .Values.advancedConfig.cronSecond | quote }}
  {{- end }}
  {{- if .Values.advancedConfig.errorLoggingChat }}
  ERROR_LOGGING_CHAT: {{ .Values.advancedConfig.errorLoggingChat | quote }}
  {{- end }}
  {{- if .Values.advancedConfig.debug }}
  DEBUG: {{ .Values.advancedConfig.debug | quote }}
  {{- end }}
{{- end }}
