apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rss-to-telegram-bot.fullname" . }}
  labels:
    {{- include "rss-to-telegram-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  TOKEN: {{ .Values.config.token | quote }}
  MANAGER: {{ .Values.config.manager | quote }}
  {{- if .Values.config.telegraphToken }}
  TELEGRAPH_TOKEN: {{ .Values.config.telegraphToken | quote }}
  {{- end }}
  {{- if .Values.advancedConfig.apiHash }}
  API_HASH: {{ .Values.advancedConfig.apiHash | quote }}
  {{- end }}
